name: Post welcome comment
on:
  push:
    branches:
      - welcome-workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

